spring:
  datasource:
    url: jdbc:mysql://localhost:3306/noproject?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      file-size-threshold: 200MB
      max-request-size: 200MB
  cache:
    type: redis
    redis:
      time-to-live: 20000
      cache-null-values: false
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
      jackson:
        default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8880
  tomcat:
    uri-encoding: UTF-8
  ip: localhost

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.myproject.entity
  map-underscore-to-camel-case: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    org.mybatis: debug
    com.example.myproject: debug
files:
  upload:
    path01: /E:/files/
    path02: /E:/Avatar/



